[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"
GeometricProblems = "18cb22b4-ad41-5c80-9c5f-710df63fbdc9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
